// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace authAPI.Model;

public partial class Product
{
    public Guid ProductId { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public decimal? Price { get; set; }

    public long? StockQuantity { get; set; }
}